version: '2'

services:
  nginx-php-fpm:
    image: richarvey/nginx-php-fpm:latest
    restart: always
    ports:
      - "80:80"
      - "89:89"
    volumes:
      - "./webroot/:/var/www/html/:rw"
      - "./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./conf/nginx/sites-enabled/:/etc/nginx/sites-enabled/:ro"
